### ISSUE TITLE
Pass dictionary as a query parameter

### ISSUE THREAD

**Issue by Bulletninja** [art1415926535/graphene-sqlalchemy-filter#10]
Is it possible to pass a filter as a query parameter? 
That is defining something like:
`
query($filters: Filter!){ ... }
`
And pass a dictionary to it (a.k.a. assign it to $filters) ? What type would `Filter` be?

**Comment by art1415926535** [comment]
The type name is the same as the Python class name.

e.g. https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/master/examples/clients_and_records/filters.py

Query
```graphql
query ($clientsFilter: ClientsFilter!){
  allClients(filters: $clientsFilter){
    edges{
      node{
        id
      }
    }
  }
}
```

Query variables
```json
{
  "clientsFilter": {"nameIn": ["Ally", "Blayze"]}
}
```
