### ISSUE TITLE
Optimizing MySQL queries

### ISSUE THREAD

**Issue by babaMar** [art1415926535/graphene-sqlalchemy-filter#15]
More a question than an issue.

I'm noticing that rendered MySQL queries are sometimes un-optimized, e.g.
```
SELECT table_1.id AS table_1_id, anon_1.id AS anon_1_id, anon_1.first_name AS anon_1_first_name, anon_1.last_name AS anon_1_last_name, anon_1.email AS anon_1_email 
FROM table_1 INNER JOIN (SELECT cglookup_persons.id AS id, cglookup_persons.first_name AS first_name, cglookup_persons.last_name AS last_name, cglookup_persons.email AS email 
FROM cglookup_persons ORDER BY cglookup_persons.id ASC) AS anon_1 ON anon_1.id = table_1.person 
WHERE table_1.id IN (2199927)
```
the nested query causes the entire table to be loaded into a hash table to be first sorted only then to be completely excluded by the join.

Skipping the `ORDER BY` would be enough to greatly reduce the execution time, something like

```
SELECT table_1.id AS table_1_id, anon_1.id AS anon_1_id, anon_1.first_name AS anon_1_first_name, anon_1.last_name AS anon_1_last_name, anon_1.email AS anon_1_email 
FROM table_1 INNER JOIN cglookup_persons AS anon_1 ON anon_1.id = table_1.person 
WHERE table_1.id IN (2199927)
```

is this achievable in any way? I guess is related to the sorting, so I'm going to try that, though I was wondering if you have some experience with it to avoid side effects.

**Comment by art1415926535** [comment]
graphene-sqlalchemy [adds sorting by default](https://github.com/graphql-python/graphene-sqlalchemy/blob/5eb5559a1ac63bdcd42f8142f9d72e99ebd3eda3/graphene_sqlalchemy/enums.py#L168). graphene-sqlalchemy-filter simply receives data from the request.
https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/f6c2123d4f19c99e2d48c342088f9ec7f09cb667/graphene_sqlalchemy_filter/connection_field.py#L252

You can disable the default value using the following trick:

```python
from graphene_sqlalchemy_filter import FilterableConnectionField
from graphene_sqlalchemy_filter.connection_field import (
    FilterableFieldFactory, NestedFilterableConnectionField
)


class DisableDefaultSort:
    def __init__(self, connection, *args, **kwargs):
        kwargs.setdefault(
            "sort", connection.Edge.node._type.sort_argument(
                has_default=False
            )
        )
        super().__init__(connection, *args, **kwargs)


class MyNestedFilterableConnectionField(
    DisableDefaultSort,
    NestedFilterableConnectionField,
):
    pass


class CustomFilterableFieldFactory(FilterableFieldFactory):
    field_class = MyNestedFilterableConnectionField


class MyFilterableConnectionField(FilterableConnectionField):
    filters = {
        User: UserFilter(),
        Membership: MembershipFilter(),
        Group: GroupFilter(),
    }
    factory = CustomFilterableFieldFactory(filters)

```

**Comment by babaMar** [comment]
Thaks @art1415926535 I see the sorting is not in place now.
