### ISSUE TITLE
[Clarification] Pagination performed by python?

### ISSUE THREAD

**Issue by thobiasn** [art1415926535/graphene-sqlalchemy-filter#16]
Hello there.

Thanks for creating this library, it is helping me a lot in my current project. I saw no other direct way to contact you so I decided to post this as an issue, sorry if this is inappropriate.

I noticed in the readme under features the following line:

> pagination (first/after, last/before) are performed by python (keep this in mind when working with large amounts of data)

First I was discouraged as I will most likely be working on quite large amounts of data at some point in the future (potentially millions of rows). I looked through the repo trying to find where pagination is handled but was not able to. After some more digging, I enabled debug logging for sqlalchemy and noticed that limit and offset is sent to the database.

```
SELECT auth."user".id AS auth_user_id, auth."user".email AS auth_user_email, auth."user".password AS auth_user_password, auth."user".lastmodified AS auth_user_lastmodified, auth."user"."roleId" AS "auth_user_roleId" 
FROM auth."user" ORDER BY auth."user".lastmodified DESC 
 LIMIT %(param_1)s OFFSET %(param_2)s
```

Does your original statement still hold true or is this graphene actually handling pagination via postgres? Thanks once again.

**Comment by art1415926535** [comment]
> I saw no other direct way to contact you so I decided to post this as an issue, sorry if this is inappropriate.

It's ok.

---

> pagination (first/after, last/before) are performed by python (keep this in mind when working with large amounts of data)

This information about nested fields.
Eg `users`:
```graphql
{
  allGroups{
    edges{
      node{
        users(first: 2) {
          edges {
            node {
              id
            }
          }
        }
      }
    }
  }
}
```


```sql
SELECT "group".id AS group_id, anon_1.id AS anon_1_id, anon_1.username AS anon_1_username, anon_1.balance AS anon_1_balance, anon_1.is_active AS anon_1_is_active 
FROM "group" JOIN member AS member_1 ON "group".id = member_1.group_id JOIN (SELECT user.id AS id, user.username AS username, user.balance AS balance, user.is_active AS is_active 
FROM user) AS anon_1 ON anon_1.id = member_1.user_id 
WHERE "group".id IN (?, ?, ?, ?)
```

first/after, last/before working by `graphql_relay.connection.arrayconnection.connection_from_list_slice` in [graphene-sqlalchemy](https://github.com/graphql-python/graphene-sqlalchemy/blob/6dca2794cd85e3ae77b6c11e3ec81d9fe81175e9/graphene_sqlalchemy/fields.py#L48)


Summary:
 * first level fields (like `allGroups` ⬆) are paginated by limit&offset
 * any other fields are paginated by Python slice

**Comment by thobiasn** [comment]
Thanks for the quick and detailed response!
That is really good news for me and my project.

Have a good one :)
