### ISSUE TITLE
Model with more than one primary key

### ISSUE THREAD

**Issue by andreferreirav2** [art1415926535/graphene-sqlalchemy-filter#18]
I just bumped into the `ModelNotSupported` Exception after adding a second primary key to a model. (https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/master/graphene_sqlalchemy_filter/connection_field.py#L195)

Is there any kind of approach recomended when bumping into this scenario?

**Comment by art1415926535** [comment]
> Is there any kind of approach recomended when bumping into this scenario?

No.

I had problems writing the correct sqlachemy query when I wrote [that part](https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/f6c2123d4f19c99e2d48c342088f9ec7f09cb667/graphene_sqlalchemy_filter/connection_field.py#L258) of the module. I have time to try to solve this problem.

I will write about the results in a few days.

**Comment by art1415926535** [comment]
Fixed in version [1.11.0](https://pypi.org/project/graphene-sqlalchemy-filter/1.11.0/).

If you are using sqlite:
  * [required](https://stackoverflow.com/a/45335411) `sqlite3.sqlite_version_info >= (3, 15, 2)`
