### ISSUE TITLE
How to use variables with filters

### ISSUE THREAD

**Issue by jackarailo** [art1415926535/graphene-sqlalchemy-filter#24]
Haven't managed to use variables with filters, is there a way to do so?

for instance I'd like to have sth like

`query users($filter: UserFilter) {
    users(filters: $filter) {
        edges {
            node {
                id
                name
            }
        }
    }
}`

with variables:

`{
    "filter":
    {
        "name": "joe"
    }
}`

**Comment by art1415926535** [comment]
> with variables:
> `{ "filtered": { "name": "joe" } }`

It should be like this `{ "filter": { "name": "joe" } }`

**Comment by jackarailo** [comment]
sorry had a typo this doesn't seem to work for me..

**Comment by art1415926535** [comment]
Check your code 🤷‍♂️  or share project example.

---
Example from repo:
https://github.com/art1415926535/graphene-sqlalchemy-filter/tree/master/examples/users_and_groups

![image](https://user-images.githubusercontent.com/5222234/89172523-72b73080-d58b-11ea-9d6b-88e651aa4198.png)

![image](https://user-images.githubusercontent.com/5222234/89172429-4dc2bd80-d58b-11ea-83fa-ab10b4d52c40.png)
