### ISSUE TITLE
How to use without Relay?

### ISSUE THREAD

**Issue by JBrVJxsc** [art1415926535/graphene-sqlalchemy-filter#25]
Hey thank you for this great lib and it solves a lot of my problems.
In my use case, I don't really need Relay and the Relay kinda makes the query confusing as we need to add `edges` and `node` etc.
I'd like to keep the normal GraphQL query syntax but also have the auto-generated filters.
Is there a way to accomplish this? Do we have a `FilterableField` instead of `FilterableConnectionField`?
Thank you!

**Comment by art1415926535** [comment]
Hi! All connections generated by [graphene-sqlalchemy](https://github.com/graphql-python/graphene-sqlalchemy). You need to do the whole schema yourself.

---

Check [new example](https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/master/examples/users_without_relay/graphql_schema.py). 

![image](https://user-images.githubusercontent.com/5222234/89885821-4d05d900-dbd4-11ea-9d2e-897841b327a3.png)

**Comment by JBrVJxsc** [comment]
Thank you so much!
