### ISSUE TITLE
Ignore `null` filter parameters for eq filter

### ISSUE THREAD

**Issue by AlexEshoo** [art1415926535/graphene-sqlalchemy-filter#31]
If I have a query written like:

```gql
query myQuery ($myFieldFilter: ID) {
  myType (filters: {myField: $myFieldFilter}) {
    myField
}
```
If I pass the parameter `$myFieldFilter` as `null`, I would like to essentially ignore the filtering entirely. This would allow me on the front end to not have to modify the structure of the query itself. It seems there is already a way to explicitly find `null` values with the filter type: `myFieldIsNull`. I was able to achieve this by modifying the function:
```python
def _eq_filter(field: 'Column', value: 'Any') -> 'Any':
    if value is None:
        return True  # ignore filter

    column_type = field.type
    if isinstance(column_type, postgresql.ARRAY):
        value = cast(value, column_type)

    return field == value
```
This is perhaps not the desired behavior of the filter in general so perhaps a setting in the `Meta` class to toggle the functionality would be desirable. Not sure if this is functionality other people would find useful, just wanted to share my experience.

**Comment by art1415926535** [comment]
This breaks compatibility and requires rethinking other filters (for consistency).

Overriding the default filtering functions in a specific project looks cleaner.

---

In your case, I advise you to move the filter field into a variable.
```graphql
query myQuery ($myTypeFilters: MyTypeFilter) {
  myType (filters: $myTypeFilters) {
    myField
  }
}
```
And pass `myField` only if needed (`{"myTypeFilters": {}}`, `{"myTypeFilters": {"myField": 1}}`).

**Comment by AlexEshoo** [comment]
I had not thought to do that, but I think that will work well, thanks for the suggestion.
