### ISSUE TITLE
AttributeError: columns

### ISSUE THREAD

**Issue by cahna** [art1415926535/graphene-sqlalchemy-filter#32]
Seeing the following error after updating package version from `1.11.1` to `1.12.0`:

```
my_code/graphql/filters/specimen.py:7: in <module>
    class SpecimenFilter(FilterSet):
.tox/py38/lib/python3.8/site-packages/graphene/utils/subclass_with_meta.py:52: in __init_subclass__
    super_class.__init_subclass_with_meta__(**options)
.tox/py38/lib/python3.8/site-packages/graphene_sqlalchemy_filter/filters.py:292: in __init_subclass_with_meta__
    filters_fields = cls._generate_default_filters(model, fields)
.tox/py38/lib/python3.8/site-packages/graphene_sqlalchemy_filter/filters.py:511: in _generate_default_filters
    model_fields = cls._get_model_fields_data(model, field_filters.keys())
.tox/py38/lib/python3.8/site-packages/graphene_sqlalchemy_filter/filters.py:609: in _get_model_fields_data
    column = attr.columns[0]
.tox/py38/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:977: in __getattr__
    return self._fallback_getattr(key)
.tox/py38/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:951: in _fallback_getattr
    raise AttributeError(key)
E   AttributeError: columns
```

`specimen.py` looks like:

```python
class SpecimenFilter(FilterSet):
    class Meta:
        model = SpecimenModel
        fields = {
            "type": ["eq", "ne", "in", "not_in"],
            "status": ["eq", "ne"],
            "group": ["eq"],
            "identifier": ["eq", "ne", "like", "ilike", "contains"],
            "created_at": ["gt", "lt", "gte", "lte"],
            "updated_at": ["gt", "lt", "gte", "lte"],
        }

    is_ready = graphene.Boolean()

    @staticmethod
    def is_ready_filter(info, query, value):
        ready = SpecimenModel.is_ready  # this is a hybrid_property that performs some joins
        return ready if value else not ready
```

It appears this commit introduces the issue: https://github.com/art1415926535/graphene-sqlalchemy-filter/commit/2562ad78ea42bde29aa65be2936e71437fb948dd

I am still investigating. Wanted to post the issue early in case this is a regression from the most-recent release. I will update with more when/if I gain more insight.

Did I miss a breaking API change or other deprecation?
Thanks!

**Comment by cahna** [comment]
I tried changing `@staticmethod` to `@classmethod` for the custom filter and using a `@hybrid_method` on the model that returns a `sqlalchemy.sql.expression` to generate the value for `filter_`, but I get the same error:

filters/specimen.py:
```python
   @classmethod
    def is_ready_filter(cls, info, query, value):
        ready = SpecimenModel.filter_is_ready()

        if value:
            filter_ = ready
        else:
            filter_ = not ready

        return query, filter_
```

models/specimen.py:
```python
    @hybrid_method
    def filter_is_ready(self):
        a = aliased(ModelA, name="a")
        b = aliased(ModelB, name="b")
        c = aliased(ModelC, name="c")

        return and_(
           # ... ~50 lines of conditions, including sub-queries with joins
        )

```

**Comment by cahna** [comment]
Using a debugger, I have found that the error occurs for [`db.relationship()` attributes](https://docs.sqlalchemy.org/en/13/orm/internals.html#sqlalchemy.orm.RelationshipProperty). These values are of type [`sqlalchemy.orm.RelationshipProperty`](https://github.com/sqlalchemy/sqlalchemy/blob/fc612d17145453ad95e5f9ba6a40ba70d2f507c3/lib/sqlalchemy/orm/relationships.py#L97) and [do not have a `columns` attribute](https://github.com/sqlalchemy/sqlalchemy/blob/fc612d17145453ad95e5f9ba6a40ba70d2f507c3/lib/sqlalchemy/orm/relationships.py#L980), thus causing the errors.

```
class SpecimenModel(db.Model):
    # ...
    group = db.relationship("GroupModel", backref=db.backref("specimens", lazy=True))
```

I believe this is a regression and expect anyone else using sqlalchemy ORM to see the same errors with relationships.

**Comment by cahna** [comment]
I had a relationship field listed in the `FilterSet.Meta.fields`. Removing the relationship field from the available filters and replacing the filter with a custom "simple filter" method fixes the error. I have reproduced the error in this commit: https://github.com/cahna/graphene-sqlalchemy-filter/pull/1/files

I suppose it is not possible to automatically filter by an ORM relationship, so this error is to be expected?

**Comment by art1415926535** [comment]
Hm... I don't know much about alchemy, such as when no columns (`len(attr.columns) == 0`) can be returned. Maybe add a comment like this?

https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/fd824a2dadeb15b1ac069e04c946502dc22bf96d/graphene_sqlalchemy_filter/filters.py#L609-L614

**Comment by cahna** [comment]
That could work nicely. Thanks for the follow-up
