### ISSUE TITLE
Support for field synonyms 

### ISSUE THREAD

**Issue by sreerajkksd** [art1415926535/graphene-sqlalchemy-filter#34]
I have a requirement to expose the actual id of the table back to the user. By default, id will be converted to graphql node id and the only way around is to create a synonym something like this in the model definition.
```python
from sqlalchemy.orm import synonym
.
.
.
class SomeModel(Base):
     __tablename__ = 'changelog'
     id = Column(BigInteger, primary_key=True)
     db_id = synonym('id)
```

Looks like that is not supported in graphene-sqllachemy-filter yet. (I'm using FilterableConnectionField)

**Comment by sreerajkksd** [comment]
I managed to fix this by using a static custom filter.

```python
    @staticmethod
    def db_id_filter(info, query, value):
        return SomeModel.id == value
```

**Comment by sreerajkksd** [comment]
Since we have an easy work around here, I don't really want to implement this feature considering that we don't usually create synonyms for everything. Closing this issue for now.

**Comment by art1415926535** [comment]
> id will be converted to graphql node id

graphene-sqllachemy does this, not graphene-sqllachemy-filter.

---


In my projects I do like this:
```python

class ArticleFilter(FilterSet):
    class Meta:
        model = Article
        fields = {'id': [...]}


class InternalID(graphene.Interface):
    internal_id = graphene.Int(required=True)

    def resolve_internal_id(self, info):
        return self.id


class ArticleNode(SQLAlchemyObjectType):
    class Meta:
        model = Article
        interfaces = (graphene.relay.Node, InternalID)
        connection_field_factory = MyFilterableConnectionField.factory

```

Result:
![image](https://user-images.githubusercontent.com/5222234/95358499-cd457380-08d1-11eb-9e6f-6f016ae459b7.png)
