### ISSUE TITLE
Postgres list contains value

### ISSUE THREAD

**Issue by bgorges** [art1415926535/graphene-sqlalchemy-filter#4]
Maybe I am missing something obvious, but how would I go about writing a contains filter for postgres?

This is the class method because I am modifying the query. 
```
@classmethod
def in_old_ids_filter(cls, info, query, value):
    has_id = cls.aliased(query, Model, name='in_old_ids')

   query = query.filter(Model.old_ids.contains(value))  # postgres sqlalchemy

   return query, ???
```

Thanks!

**Comment by bgorges** [comment]
Quickest turn-around time...

I used the staticmethod:

```
@staticmethod
def in_old_ids_filter(info, query, value):
   return Model.old_ids.contains(f'{{{value}}}')
```

Where I am attaching curly braces on the outside of the value to conform with postgres expectations. ( `{{` makes a curly brace in an f-string.)

Pretty sure this isn't an issue for this module to take care of, but I'll let someone else reopen it if it is.

**Comment by art1415926535** [comment]
I want to add all [pg array comparator functions](https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#sqlalchemy.dialects.postgresql.ARRAY.Comparator) later.

And then in your case it will be
```python
class ModelFilter(FilterSet):
   class Meta:
       model = Model
       fields = {'old_ids': ['contains']}
```

Leave this issue open until release feature.

**Comment by art1415926535** [comment]
Check [new version](https://pypi.org/project/graphene-sqlalchemy-filter/1.8.0/).

Filters are now available: contains, contained_by and overlap.

```graphql
{
  a: allObjects(filters: {oldIdsContains: 1}) { edges { node { id } } }
  b: allObjects(filters: {oldIdsContains: [2, 3]}) { edges { node { id } } }
}
```
