### ISSUE TITLE
totalCount() via database `count()`?

### ISSUE THREAD

**Issue by docelic** [art1415926535/graphene-sqlalchemy-filter#41]
Hey,

I have a query like this:

```
      someObjects(filters: {and: [{status: "DONE"}]}) {
        totalCount
      }
```

This is producing `totalCount` by retrieving all this in Python and doing a `len()` on it.

What's the suggested way to make this be a DB query using `count`?
(If the only solution is to rewrite the whole query in a different way or to provide my own/custom field which does `count()`, that's a fine too.)

**Comment by art1415926535** [comment]
I added a new [example](https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/7baa457d6ffdb790354caf1d3c6a00d8c99e4165/examples/users_with_count/). 

In short:
https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/7baa457d6ffdb790354caf1d3c6a00d8c99e4165/examples/users_with_count/graphql_schema.py#L11-L15

https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/7baa457d6ffdb790354caf1d3c6a00d8c99e4165/examples/users_with_count/graphql_schema.py#L25-L28

It uses graphene-sqlalchemy [feature](https://github.com/graphql-python/graphene-sqlalchemy/blob/20ecaeadf2144b88555a3daf1a04e31b7f2ff95a/graphene_sqlalchemy/fields.py#L67).

**Comment by docelic** [comment]
Fabulous! Thanks Artem as always.

**Comment by PriyatamNayak** [comment]
@art1415926535 
How we can count  or average without relay 
dont want to see the contents  with node and edge
Could you please help me??

**Comment by art1415926535** [comment]
If you are not using the graphene-sqlalchemy relay, then you need to solve this problem by building on your schema. For example, make a separate field and write your resolver for it.

**Comment by docelic** [comment]
I finally got to trying this suggestion today. But I realized that the given solution is the standard way how I already implement `totalCount`. It works by counting objects in Python rather than using a db-level `count()` function.
