### ISSUE TITLE
How to make a filter field required?

### ISSUE THREAD

**Issue by oathexodus** [art1415926535/graphene-sqlalchemy-filter#44]
Since the dataset is very large in my case, I want to have a feature to limit the size of a response dataset. For example, I want to make a filter field like `timestamp` required. Is this a correct way?

Thanks for your great works!

**Comment by art1415926535** [comment]
I think, it's wrong way. Your clients anyway may set very large timestamp range. You need to look at the pagination. For example, check that the value of `first` and` last` is less than some value.

You need something like this:
`{allUsers(first: 100000){id}}` -> error
`{allUsers(last: 100000){id}}` -> error
`{allUsers(first: 10){id}}` -> ok
`{allUsers(last: 10){id}}` -> ok

**Comment by oathexodus** [comment]
That's good but the key is how to validate input fields. Maybe this is not related to graphene-sqlalchemy-filter, right?

**Comment by art1415926535** [comment]
Yes, it has nothing to do with graphene-sqlalchemy-filter.

You can validate input fields in your resolver.

**Comment by oathexodus** [comment]
Thanks
