### ISSUE TITLE
Intercept query to verify the token

### ISSUE THREAD

**Issue by dev-tecnoinfo** [art1415926535/graphene-sqlalchemy-filter#45]
How can I submit a token in a query and intercept to verify that the token is valid before performing the data search?

**Comment by art1415926535** [comment]
You can check token in graphene middleware https://docs.graphene-python.org/en/latest/execution/middleware/ or eg middleware of your server framewor.

**Comment by dev-tecnoinfo** [comment]
`all_roles = filters.MyFilterableConnectionField(RoleConnection, middleware=[AuthorizationMiddleware()])`

I tried this way, but returned an error:  `TypeError: '<' not supported between instances of 'RoleFilter' and 'list'`

**Comment by art1415926535** [comment]
You only need to add middleware to view https://github.com/graphql-python/graphql-server/blob/master/docs/flask.md

```python
app.add_url_rule('/graphql', view_func=GraphQLView.as_view(
    'graphql',
    schema=schema,
    graphiql=True,
    middleware=[AuthorizationMiddleware()],
))
```
