### ISSUE TITLE
TypeError: 'String' object is not callable

### ISSUE THREAD

**Issue by frenchtoast747** [art1415926535/graphene-sqlalchemy-filter#5]
First off, this is awesome! I'm still not 100% familiar with the intricacies of SQLAlchemy and it would have taken me a while to write something as complete as this library. Thanks!

---

I have a relatively simple setup.
Model:
```
class Transaction(Base):
    # ...
    memo = Column(Text)
    # ...
```
Filter:
```
class TransactionFilter(FilterSet):
    class Meta:
        model = Transaction
        fields = {
            'memo': [...],
        }
```
However, when I run this, I get the following error:
```
Traceback (most recent call last):
  ...
    class TransactionFilter(FilterSet):
  File "/home/aaron/.virtualenvs/api/lib/python3.6/site-packages/graphene/utils/subclass_with_meta.py", line 52, in __init_subclass__
    super_class.__init_subclass_with_meta__(**options)
  File "/home/aaron/.virtualenvs/api/lib/python3.6/site-packages/graphene_sqlalchemy_filter/filters.py", line 262, in __init_subclass_with_meta__
    filters_fields = cls._generate_default_filters(model, fields)
  File "/home/aaron/.virtualenvs/api/lib/python3.6/site-packages/graphene_sqlalchemy_filter/filters.py", line 515, in _generate_default_filters
    expressions, field_name, field_type, field_object['nullable']
  File "/home/aaron/.virtualenvs/api/lib/python3.6/site-packages/graphene_sqlalchemy_filter/filters.py", line 563, in _generate_filter_fields
    filter_field = field_type(description=doc)
TypeError: 'String' object is not callable
```
The error is coming from `_generate_default_filters` from the following line:
```
field_type = convert_sqlalchemy_type(
    column_type, field_object['column']
)
```
The `field_type` that is returned is an instance of `graphene.String()`, which is itself not callable. I'm still familiarizing myself with the code, but I _think_ this should be getting the class `String` and not an instance. My workaround (that seems to work) is to tack `__class__` on the end of that call:
```
field_type = convert_sqlalchemy_type(
    column_type, field_object['column']
).__class__
```

**Comment by frenchtoast747** [comment]
I'm current using `graphene-sqlalchemy==2.1.0`

**Comment by frenchtoast747** [comment]
It looks like `graphene-sqlalchemy==2.2.1` [(here)](https://github.com/graphql-python/graphene-sqlalchemy/compare/2.2.0...2.2.1) introduced a change to the what is returned by `convert_sqlalchemy_type`.

I tried updating `graphene-sqlalchemy` on my end, but a bunch of things broke in the process. I'm not sure there is much more you could do here other than check to see if you got a class or an instance for backward-compatibility. Feel free to close.

**Comment by art1415926535** [comment]
Yes. `graphene-sqlalchemy<2.2.1` breaks that part of code. That's why I'm added `graphene-sqlalchemy>=2.2.1,<3` to requirements.

I will try to add support for older versions.

**Comment by art1415926535** [comment]
Hey @frenchtoast747, check [new version](https://pypi.org/project/graphene-sqlalchemy-filter/1.9.1/). New requirements: `graphene-sqlalchemy>=2.1.0,<3`.

Feel free to reopen the question if you have questions.

**Comment by frenchtoast747** [comment]
Awesome, thanks so much!
