### ISSUE TITLE
How to you filter many to many table?

### ISSUE THREAD

**Issue by ericleemz** [art1415926535/graphene-sqlalchemy-filter#57]
I'd like to filter many to many table like user and tags

```
class MyFilter(Filterset):
    class Meta:
        model = User
    tag_id = graphene.ID()
    @classmethod
    def tag_id_filter(cls, info, query, value):
        user_tag = cls.aliased(query, Tag, name='user_tag')
        query = query.join(user_tag, and_(User.id == user_tag.user_id, user_tag.tag_id.is_(value))
        return query
```

this code makes an error
like below

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''1' ORDER BY user.id ASC) \\nWHERE (SELECT user.id AS user_id_1, user.created AS u' at ~~~ blablabla

the number '1' before ORDER BY is tag_id which is value in function tag_id_filter

**Comment by ericleemz** [comment]
I solved the problem.

since I didn't add filter_ which is described on the home page, It was necessary to add filter_ 
because when I looked at the last query it shows the join query at where clause. I don't know why but the same join query appeared twice at FROM and WHERE.
So I added filter like filter_ = user_tag.tag_id.__eq__(value)
Then It works great!

**Comment by art1415926535** [comment]
Yes! The library expects to receive from function `(query, filter)` or `(filter)`, not just `(query)`.

Also, `filter_ = user_tag.tag_id == value` will more pythonic.
