### ISSUE TITLE
How to do multiple level joins

### ISSUE THREAD

**Issue by sreerajkksd** [art1415926535/graphene-sqlalchemy-filter#58]
This is more of a question than an issue.

I want to perform multi join based filter, but I'm having difficulty in implementing it using sqlalchemy_filter.

Eg: This is the schema.

```
SchoolType:
     id
     type = (can be goverment or private)

School:
     id
     name
     type_id (references school type)

Student:
     id
     name
     school_id (referebnces school)
```

 I want to add a school_type filter for student class. How do I do that ?

**Comment by art1415926535** [comment]
There is an example of filter function https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/6b59c1f40a5f50cf3888171fc58a0b0d9f516436/examples/users_and_groups/filters.py#L61
