### ISSUE TITLE
impliment custom resolver together with filters or a must call method

### ISSUE THREAD

**Issue by kimutaiRop** [art1415926535/graphene-sqlalchemy-filter#60]
is there a way that I can impliment a method that must be called everytime am using it to fetch data coz I realised that custom resolver makes the filters not work anymore

**Comment by kpraznik** [comment]
I would like to know this as well.

Because I have a viewer root node that has a user field. The user field has got a location connection field with filters but they don't work due to a custom resolver for the viewer and the user.

**Comment by art1415926535** [comment]
Yes, you can.

https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/master/examples/users_without_relay/graphql_schema.py#L18
