### ISSUE TITLE
Filters without manual filters= option

### ISSUE THREAD

**Issue by docelic** [art1415926535/graphene-sqlalchemy-filter#7]
Hey Artem,

In issue #6 we also discussed that your syntax for creating `FilterableConnectionField`s requires argument `filters=`:

```python
class ModelAFilter(FilterSet):
  # ...
class ModelA(ObjectType):
  Meta:
    model = ModelAModel
    # ...

class RootQuery(graphene.ObjectType):
  something = FilterableConnectionField('ModelA', filters=ModelAFilter()) # <--- 
```

Could you somehow make it so that the ModelAFilter is specified directly inside ModelA or it's meta class, so that one does not have to manually pass the `filters=` option when creating a field?

Thanks!

**Comment by art1415926535** [comment]
Hi. Last week I worked on methods for solving #6. It's almost ready. I have to write tests. Soon I will announce new features. One of the side effects of my solution closes this issue.

**Comment by art1415926535** [comment]
New version [released](https://pypi.org/project/graphene-sqlalchemy-filter/1.10.0/). New documentation section [here](https://github.com/art1415926535/graphene-sqlalchemy-filter/blob/f326aaf982f1a2e6533e01fa4594e3d2707656c3/README.md#filter-registration-and-nested-fields-filters).
