### ISSUE TITLE
'Request' object has no attribute 'id'

### ISSUE THREAD

**Issue by Xindi-Li** [art1415926535/graphene-sqlalchemy-filter#9]
In my models, I renamed the column `id` to be `request_id`

```
class Request(Base):

    __tablename__ = "requests"

    request_id = Column("id", String, primary_key=True)

    datasets = relationship("Dataset")
```
The filter gave me this error `"message": "'Request' object has no attribute 'id'",` when I queried `datasets`. But if I used `id=Column(String, primary_key=True)`, it worked. Any idea?

**Comment by art1415926535** [comment]
Fixed in version [10.0.1](https://pypi.org/project/graphene-sqlalchemy-filter/1.10.1/).
